import React from 'react';
import { Text } from 'react-native';
import { MaterialCommunityIcons, Ionicons, FontAwesome5 } from '@expo/vector-icons';

type IconDef =
  | { set: 'mci'; name: keyof typeof MaterialCommunityIcons.glyphMap }
  | { set: 'ion'; name: keyof typeof Ionicons.glyphMap }
  | { set: 'fa5'; name: string };

// Super categories
const SUPER_ICON_MAP: Record<string, IconDef> = {
  '🎬': { set: 'mci', name: 'filmstrip' },
  '🎵': { set: 'mci', name: 'music-note' },
  '⚽': { set: 'ion', name: 'football' },
  '🏛️': { set: 'mci', name: 'pillar' },
  '🔬': { set: 'mci', name: 'flask-round-bottom' },
  '🍽️': { set: 'mci', name: 'silverware-fork-knife' },
  '🌍': { set: 'mci', name: 'earth' },
  '🎮': { set: 'mci', name: 'gamepad-variant' },
  '✨': { set: 'mci', name: 'diamond-stone' },
  '🎨': { set: 'mci', name: 'palette' },
  '🌱': { set: 'mci', name: 'sprout' },
  '🧠': { set: 'mci', name: 'head-lightbulb-outline' },
};

// Clusters
const CLUSTER_ICON_MAP: Record<string, IconDef> = {
  // SCREEN
  '📺': { set: 'mci', name: 'television-classic' },
  '🎬': { set: 'mci', name: 'movie-open-outline' },
  '🎌': { set: 'mci', name: 'animation-play' },
  // SOUND
  '🎤': { set: 'mci', name: 'microphone-variant' },
  '🎼': { set: 'mci', name: 'music' },
  '🎸': { set: 'mci', name: 'guitar-electric' },
  // ARENA
  '🥊': { set: 'mci', name: 'boxing-glove' },
  '🎮': { set: 'mci', name: 'gamepad-variant' },
  '🏀': { set: 'mci', name: 'basketball' },
  // LEGENDS
  '🏛️': { set: 'mci', name: 'bank' },
  '📜': { set: 'mci', name: 'script-text' },
  '⚡': { set: 'mci', name: 'lightning-bolt' },
  // LAB
  '🚀': { set: 'mci', name: 'rocket-launch' },
  '⚗️': { set: 'mci', name: 'flask' },
  '🤖': { set: 'mci', name: 'robot' },
  // GLOBE
  '🍷': { set: 'mci', name: 'glass-wine' },
  '🗣️': { set: 'mci', name: 'account-voice' },
  '✈️': { set: 'mci', name: 'airplane' },
  // ART
  '🏗️': { set: 'mci', name: 'office-building' },
  '👗': { set: 'mci', name: 'tshirt-crew' },
  '🖌️': { set: 'mci', name: 'brush' },
  // LIFE
  '🫀': { set: 'mci', name: 'heart-pulse' },
  '🐾': { set: 'mci', name: 'paw' },
  '🌿': { set: 'mci', name: 'leaf' },
  // MIND
  '📖': { set: 'mci', name: 'book-open-variant' },
  '🔢': { set: 'mci', name: 'calculator-variant' },
  '💭': { set: 'mci', name: 'thought-bubble' },
  // Fallback
  '📁': { set: 'mci', name: 'folder-outline' },
};

// Individual themes by ID
const THEME_ICON_MAP: Record<string, IconDef> = {
  // Combat & Athlé
  ARE_BOXE: { set: 'mci', name: 'boxing-glove' },
  ARE_CROS: { set: 'mci', name: 'dumbbell' },
  ARE_PIST: { set: 'mci', name: 'bike' },
  ARE_ESCA: { set: 'mci', name: 'carabiner' },
  ARE_ESCR: { set: 'mci', name: 'sword' },
  ARE_GYMN: { set: 'mci', name: 'human-handsup' },
  ARE_HALT: { set: 'mci', name: 'weight-lifter' },
  ARE_JUDO: { set: 'mci', name: 'karate' },
  ARE_KARA: { set: 'mci', name: 'karate' },
  ARE_LANC: { set: 'mci', name: 'bullseye-arrow' },
  ARE_LUTT: { set: 'mci', name: 'account-group' },
  ARE_FOND: { set: 'mci', name: 'run-fast' },
  ARE_MMA: { set: 'mci', name: 'boxing-glove' },
  ARE_THAI: { set: 'mci', name: 'mixed-martial-arts' },
  ARE_NATA: { set: 'mci', name: 'swim' },
  ARE_SAUT: { set: 'mci', name: 'human-male-height-variant' },
  ARE_SPRI: { set: 'mci', name: 'lightning-bolt' },
  ARE_SUMO: { set: 'mci', name: 'kabaddi' },
  ARE_TIRA: { set: 'mci', name: 'bow-arrow' },
  ARE_TRIA: { set: 'mci', name: 'trophy-variant' },
  // E-sport & Gaming
  ARE_APEX: { set: 'mci', name: 'parachute' },
  ARE_COD: { set: 'mci', name: 'pistol' },
  ARE_CSGO: { set: 'mci', name: 'crosshairs' },
  ARE_DOTA: { set: 'mci', name: 'castle' },
  ARE_FIFA: { set: 'mci', name: 'soccer' },
  ARE_FGT: { set: 'mci', name: 'controller-classic' },
  ARE_FORT: { set: 'mci', name: 'axe-battle' },
  ARE_HRTH: { set: 'mci', name: 'cards-playing' },
  ARE_LOL: { set: 'mci', name: 'shield-sword' },
  ARE_OVER: { set: 'mci', name: 'shield-half-full' },
  ARE_PUBE: { set: 'mci', name: 'target' },
  ARE_RSIX: { set: 'mci', name: 'bomb' },
  ARE_ROCK: { set: 'mci', name: 'car-sports' },
  ARE_SIMR: { set: 'mci', name: 'flag-checkered' },
  ARE_SSB: { set: 'mci', name: 'star-shooting' },
  ARE_MINE: { set: 'mci', name: 'timer' },
  ARE_STAR: { set: 'mci', name: 'strategy' },
  ARE_TEKK: { set: 'mci', name: 'fencing' },
  ARE_VALO: { set: 'mci', name: 'crosshairs-gps' },
  ARE_WOW: { set: 'mci', name: 'sword-cross' },
  // Sports de Balle
  ARE_BADM: { set: 'mci', name: 'badminton' },
  ARE_BASE: { set: 'mci', name: 'baseball' },
  ARE_BASK: { set: 'mci', name: 'basketball' },
  ARE_BEAC: { set: 'mci', name: 'volleyball' },
  ARE_BILL: { set: 'mci', name: 'billiards' },
  ARE_BOWL: { set: 'mci', name: 'bowling' },
  ARE_CRIC: { set: 'mci', name: 'cricket' },
  ARE_USFT: { set: 'mci', name: 'football-helmet' },
  ARE_FOOT: { set: 'mci', name: 'soccer' },
  ARE_GOLF: { set: 'mci', name: 'golf' },
  ARE_HAND: { set: 'mci', name: 'handball' },
  ARE_HOCK: { set: 'mci', name: 'hockey-sticks' },
  ARE_LACR: { set: 'mci', name: 'racquetball' },
  ARE_PADE: { set: 'mci', name: 'tennis' },
  ARE_RUGB: { set: 'mci', name: 'rugby' },
  ARE_SQUA: { set: 'mci', name: 'racquetball' },
  ARE_PING: { set: 'mci', name: 'table-tennis' },
  ARE_TENN: { set: 'mci', name: 'tennis' },
  ARE_VOLL: { set: 'mci', name: 'volleyball' },
  ARE_WPOL: { set: 'mci', name: 'water-polo' },
  // Architecture
  ART_GAUD: { set: 'mci', name: 'home-modern' },
  ART_BRUT: { set: 'mci', name: 'warehouse' },
  ART_GOTH: { set: 'mci', name: 'church' },
  ART_VERS: { set: 'mci', name: 'castle' },
  ART_LOIR: { set: 'mci', name: 'town-hall' },
  ART_DUBA: { set: 'mci', name: 'city-variant' },
  ART_ECOA: { set: 'mci', name: 'leaf-circle' },
  ART_ROMA: { set: 'mci', name: 'arch' },
  ART_SKYS: { set: 'mci', name: 'domain' },
  ART_WOND: { set: 'mci', name: 'pyramid' },
  ART_MODR: { set: 'mci', name: 'office-building-cog' },
  ART_OPER: { set: 'mci', name: 'theater' },
  ART_PAGO: { set: 'mci', name: 'temple-buddhist' },
  ART_BRDG: { set: 'mci', name: 'bridge' },
  ART_STAD: { set: 'mci', name: 'stadium' },
  ART_HAUS: { set: 'mci', name: 'home-city' },
  ART_TAJM: { set: 'mci', name: 'mosque' },
  ART_GREC: { set: 'mci', name: 'pillar' },
  ART_EIFF: { set: 'mci', name: 'eiffel-tower' },
  ART_ZAHA: { set: 'mci', name: 'diamond-stone' },
  // Mode & Design
  ART_MCQU: { set: 'mci', name: 'skull-crossbones' },
  ART_DECO: { set: 'mci', name: 'shape' },
  ART_BALN: { set: 'mci', name: 'shoe-heel' },
  ART_BAUH: { set: 'mci', name: 'cube-outline' },
  ART_DIOR: { set: 'mci', name: 'flower-tulip' },
  ART_SNEA: { set: 'mci', name: 'shoe-sneaker' },
  ART_INDU: { set: 'mci', name: 'cog' },
  ART_SCAN: { set: 'mci', name: 'sofa' },
  ART_MEMP: { set: 'mci', name: 'lamp' },
  ART_COUT: { set: 'mci', name: 'scissors-cutting' },
  ART_TIME: { set: 'mci', name: 'watch' },
  ART_BIJO: { set: 'mci', name: 'necklace' },
  ART_PERF: { set: 'mci', name: 'spray' },
  ART_VUIT: { set: 'mci', name: 'bag-personal' },
  ART_CHAN: { set: 'mci', name: 'hanger' },
  ART_GUCC: { set: 'mci', name: 'sunglasses' },
  ART_HERM: { set: 'mci', name: 'horse' },
  ART_CHAI: { set: 'mci', name: 'seat' },
  ART_PUNK: { set: 'mci', name: 'lightning-bolt' },
  ART_YVES: { set: 'mci', name: 'tshirt-crew' },
  // Peinture & Sculpture
  ART_ABST: { set: 'mci', name: 'palette' },
  ART_BARO: { set: 'mci', name: 'image-frame' },
  ART_CONT: { set: 'mci', name: 'creation' },
  ART_RODI: { set: 'mci', name: 'human' },
  ART_PIGM: { set: 'mci', name: 'eyedropper' },
  ART_JAPA: { set: 'mci', name: 'fan' },
  ART_FEMM: { set: 'mci', name: 'gender-female' },
  ART_KAHLO: { set: 'mci', name: 'flower-tulip' },
  ART_IMPR: { set: 'mci', name: 'brush' },
  ART_VINCI: { set: 'mci', name: 'draw' },
  ART_MICH: { set: 'mci', name: 'hammer' },
  ART_ORSA: { set: 'mci', name: 'bank' },
  ART_LOUV: { set: 'mci', name: 'pyramid' },
  ART_PICA: { set: 'mci', name: 'cube-outline' },
  ART_POPP: { set: 'mci', name: 'spray-bottle' },
  ART_RENA: { set: 'mci', name: 'format-paint' },
  ART_ANTI: { set: 'mci', name: 'pillar' },
  ART_STRT: { set: 'mci', name: 'spray' },
  ART_SURR: { set: 'mci', name: 'head-snowflake' },
  ART_GOGH: { set: 'mci', name: 'star-shooting' },
  // Animation & Anime
  ANI_ARCA: { set: 'mci', name: 'sword' },
  ANI_DISN: { set: 'mci', name: 'castle' },
  ANI_BEBO: { set: 'mci', name: 'ship-wheel' },
  ANI_DNOT: { set: 'mci', name: 'skull' },
  ANI_DEMO: { set: 'mci', name: 'sword-cross' },
  ANI_DBZ: { set: 'mci', name: 'fire' },
  ANI_FMAB: { set: 'mci', name: 'flask' },
  ANI_JUJU: { set: 'mci', name: 'ghost' },
  ANI_AOTT: { set: 'mci', name: 'shield-sword' },
  ANI_LION: { set: 'mci', name: 'crown' },
  ANI_MYHE: { set: 'mci', name: 'shield-half-full' },
  ANI_NARU: { set: 'mci', name: 'ninja' },
  ANI_OPIE: { set: 'mci', name: 'sail-boat' },
  ANI_POKE: { set: 'mci', name: 'pokeball' },
  ANI_RATAT: { set: 'mci', name: 'chef-hat' },
  ANI_RICK: { set: 'mci', name: 'flask-round-bottom' },
  ANI_SHRE: { set: 'mci', name: 'emoticon-devil' },
  ANI_SOUP: { set: 'mci', name: 'television-classic' },
  ANI_SPID: { set: 'mci', name: 'spider-thread' },
  ANI_GHIB: { set: 'mci', name: 'cat' },
  // Cinéma
  CIN_AVAT: { set: 'mci', name: 'leaf' },
  CIN_FIGH: { set: 'mci', name: 'boxing-glove' },
  CIN_GLAD: { set: 'mci', name: 'sword' },
  CIN_HPOT: { set: 'mci', name: 'magic-staff' },
  CIN_INCE: { set: 'mci', name: 'rotate-3d-variant' },
  CIN_INDI: { set: 'mci', name: 'hat-fedora' },
  CIN_JURA: { set: 'mci', name: 'bone' },
  CIN_PARR: { set: 'mci', name: 'pistol' },
  CIN_DENT: { set: 'mci', name: 'shark-fin' },
  CIN_MATR: { set: 'mci', name: 'sunglasses' },
  CIN_PARA: { set: 'mci', name: 'stairs' },
  CIN_PULP: { set: 'mci', name: 'hamburger' },
  CIN_RETO: { set: 'mci', name: 'car-back' },
  CIN_SCRE: { set: 'mci', name: 'ghost' },
  CIN_SDAN: { set: 'mci', name: 'ring' },
  CIN_STAR: { set: 'mci', name: 'star-four-points' },
  CIN_BATN: { set: 'mci', name: 'bat' },
  CIN_TITA: { set: 'mci', name: 'ship-wheel' },
  CIN_TOYS: { set: 'mci', name: 'robot' },
  CIN_MARV: { set: 'mci', name: 'shield-half-full' },
  // Séries TV
  STV_13RW: { set: 'mci', name: 'cassette' },
  STV_BEEF: { set: 'mci', name: 'car-side' },
  STV_BCSA: { set: 'mci', name: 'phone-classic' },
  STV_BLKM: { set: 'mci', name: 'cellphone' },
  STV_BBAD: { set: 'mci', name: 'flask' },
  STV_BRID: { set: 'mci', name: 'heart' },
  STV_B99: { set: 'mci', name: 'police-badge' },
  STV_CASA: { set: 'mci', name: 'safe' },
  STV_COBR: { set: 'mci', name: 'karate' },
  STV_DARK: { set: 'mci', name: 'clock-time-eight' },
  STV_DEXT: { set: 'mci', name: 'knife' },
  STV_HOUS: { set: 'mci', name: 'pill' },
  STV_EMIL: { set: 'mci', name: 'eiffel-tower' },
  STV_EUPH: { set: 'mci', name: 'shimmer' },
  STV_FALL: { set: 'mci', name: 'radioactive' },
  STV_FARG: { set: 'mci', name: 'snowflake' },
  STV_FRND: { set: 'mci', name: 'sofa' },
  STV_GOT: { set: 'mci', name: 'crown' },
  STV_GREY: { set: 'mci', name: 'hospital-box' },
  STV_HEAR: { set: 'mci', name: 'heart-outline' },
  STV_SIMP: { set: 'mci', name: 'emoticon-happy' },
  STV_LOST: { set: 'mci', name: 'island' },
  STV_LUPIN: { set: 'mci', name: 'domino-mask' },
  STV_MAND: { set: 'mci', name: 'star-four-points' },
  STV_WEDS: { set: 'mci', name: 'umbrella' },
  STV_NARC: { set: 'mci', name: 'pistol' },
  STV_OMIT: { set: 'mci', name: 'magnify' },
  STV_OUTL: { set: 'mci', name: 'sword-cross' },
  STV_PEAK: { set: 'mci', name: 'hat-fedora' },
  STV_SEVE: { set: 'mci', name: 'brain' },
  STV_SEXE: { set: 'mci', name: 'school' },
  STV_SHER: { set: 'mci', name: 'magnify' },
  STV_SHOG: { set: 'mci', name: 'sword' },
  STV_SILO: { set: 'mci', name: 'silo' },
  STV_SQDG: { set: 'mci', name: 'circle-outline' },
  STV_STHR: { set: 'mci', name: 'bike' },
  STV_SUCC: { set: 'mci', name: 'briefcase' },
  STV_SUIT: { set: 'mci', name: 'gavel' },
  STV_TEDL: { set: 'mci', name: 'soccer' },
  STV_BEAR: { set: 'mci', name: 'chef-hat' },
  STV_BOYS: { set: 'mci', name: 'lightning-bolt' },
  STV_CROW: { set: 'mci', name: 'crown' },
  STV_TLOU: { set: 'mci', name: 'mushroom' },
  STV_OFFI: { set: 'mci', name: 'desk' },
  STV_WHIT: { set: 'mci', name: 'palm-tree' },
  STV_TRUE: { set: 'mci', name: 'star-outline' },
  STV_VIKI: { set: 'mci', name: 'axe' },
  STV_YELJ: { set: 'mci', name: 'pine-tree' },
  STV_YELL: { set: 'mci', name: 'horse' },
  STV_YOU: { set: 'mci', name: 'eye' },
  // Hits & Pop Culture
  SOU_P80S: { set: 'mci', name: 'cassette' },
  SOU_P90S: { set: 'mci', name: 'disc' },
  SOU_BEYO: { set: 'mci', name: 'crown' },
  SOU_DISC: { set: 'mci', name: 'spotlight-beam' },
  SOU_DIVA: { set: 'mci', name: 'microphone-variant' },
  SOU_EUVN: { set: 'mci', name: 'star-shooting' },
  SOU_FEST: { set: 'mci', name: 'tent' },
  SOU_FTOU: { set: 'mci', name: 'eiffel-tower' },
  SOU_KPOP: { set: 'mci', name: 'heart-multiple' },
  SOU_LATI: { set: 'mci', name: 'fire' },
  SOU_MJAC: { set: 'mci', name: 'hat-fedora' },
  SOU_ONEH: { set: 'mci', name: 'numeric-1-circle' },
  SOU_QUEE: { set: 'mci', name: 'crown' },
  SOU_RAFR: { set: 'mci', name: 'microphone' },
  SOU_RAPP: { set: 'mci', name: 'headphones' },
  SOU_REGG: { set: 'mci', name: 'music-note' },
  SOU_ROCK: { set: 'mci', name: 'guitar-electric' },
  SOU_TSWI: { set: 'mci', name: 'heart' },
  SOU_BEAT: { set: 'mci', name: 'ladybug' },
  SOU_SUMM: { set: 'mci', name: 'white-balance-sunny' },
  // Musiques de Films & Jeux
  SOU_RETR: { set: 'mci', name: 'gamepad-square' },
  SOU_AMBE: { set: 'mci', name: 'headphones' },
  SOU_ANIO: { set: 'mci', name: 'animation-play' },
  SOU_BROA: { set: 'mci', name: 'theater' },
  SOU_DISM: { set: 'mci', name: 'castle' },
  SOU_DELF: { set: 'mci', name: 'ghost' },
  SOU_EMOR: { set: 'mci', name: 'pistol' },
  SOU_GELE: { set: 'mci', name: 'television-classic' },
  SOU_HZIM: { set: 'mci', name: 'timer' },
  SOU_HORR: { set: 'mci', name: 'skull' },
  SOU_BOND: { set: 'mci', name: 'pistol' },
  SOU_GHIB: { set: 'mci', name: 'cat' },
  SOU_JWIL: { set: 'mci', name: 'star-four-points' },
  SOU_KKON: { set: 'mci', name: 'gamepad-variant' },
  SOU_MGOR: { set: 'mci', name: 'fire' },
  SOU_EPIC: { set: 'mci', name: 'sword-cross' },
  SOU_NUEM: { set: 'mci', name: 'crystal-ball' },
  SOU_INCH: { set: 'mci', name: 'controller-classic' },
  SOU_SYNT: { set: 'mci', name: 'robot' },
  SOU_WEST: { set: 'mci', name: 'horseshoe' },
  // Rock & Classiques
  SOU_ACDC: { set: 'mci', name: 'lightning-bolt' },
  SOU_BEET: { set: 'mci', name: 'piano' },
  SOU_ORCH: { set: 'mci', name: 'music-clef-treble' },
  SOU_CHOP: { set: 'mci', name: 'piano' },
  SOU_BOWI: { set: 'mci', name: 'star-shooting' },
  SOU_JAZZ: { set: 'mci', name: 'saxophone' },
  SOU_IRON: { set: 'mci', name: 'skull' },
  SOU_BACH: { set: 'mci', name: 'violin' },
  SOU_HEND: { set: 'mci', name: 'guitar-electric' },
  SOU_OPER: { set: 'mci', name: 'drama-masks' },
  SOU_LZEP: { set: 'mci', name: 'airballoon' },
  SOU_META: { set: 'mci', name: 'lightning-bolt' },
  SOU_MOZA: { set: 'mci', name: 'music-clef-treble' },
  SOU_NIRV: { set: 'mci', name: 'emoticon-happy' },
  SOU_PFLO: { set: 'mci', name: 'triangle-outline' },
  SOU_PUNK: { set: 'mci', name: 'safety-goggles' },
  SOU_RHCP: { set: 'mci', name: 'chili-mild' },
  SOU_STON: { set: 'mci', name: 'cards-diamond' },
  SOU_PIAN: { set: 'mci', name: 'piano' },
  SOU_VIVA: { set: 'mci', name: 'violin' },
  // Antiq. & M-Â
  LEG_ALEX: { set: 'mci', name: 'sword' },
  LEG_CHIV: { set: 'mci', name: 'shield-sword' },
  LEG_CHAR: { set: 'mci', name: 'crown' },
  LEG_PHAR: { set: 'mci', name: 'pyramid' },
  LEG_AZTE: { set: 'mci', name: 'sun-compass' },
  LEG_BYZA: { set: 'mci', name: 'church' },
  LEG_OTTO: { set: 'mci', name: 'mosque' },
  LEG_ROMA: { set: 'mci', name: 'pillar' },
  LEG_HUNS: { set: 'mci', name: 'horse' },
  LEG_PIRA: { set: 'mci', name: 'skull-crossbones' },
  LEG_GLAD: { set: 'mci', name: 'sword-cross' },
  LEG_JOAN: { set: 'mci', name: 'flag-variant' },
  LEG_SPAR: { set: 'mci', name: 'shield' },
  LEG_MONG: { set: 'mci', name: 'bow-arrow' },
  LEG_VIKI: { set: 'mci', name: 'axe' },
  LEG_NINJ: { set: 'mci', name: 'ninja' },
  LEG_TEMP: { set: 'mci', name: 'cross' },
  LEG_GAUL: { set: 'mci', name: 'hard-hat' },
  LEG_SILK: { set: 'mci', name: 'road-variant' },
  LEG_SAMU: { set: 'mci', name: 'karate' },
  // Hist. Moderne
  LEG_HOLL: { set: 'mci', name: 'filmstrip' },
  LEG_WALL: { set: 'mci', name: 'wall' },
  LEG_WEST: { set: 'mci', name: 'horseshoe' },
  LEG_SPAC: { set: 'mci', name: 'rocket-launch' },
  LEG_NAPO: { set: 'mci', name: 'crown' },
  LEG_VICT: { set: 'mci', name: 'hat-fedora' },
  LEG_EXPL: { set: 'mci', name: 'compass' },
  LEG_VIET: { set: 'mci', name: 'helicopter' },
  LEG_COLD: { set: 'mci', name: 'atom' },
  LEG_ATOM: { set: 'mci', name: 'radioactive' },
  LEG_BEPP: { set: 'mci', name: 'eiffel-tower' },
  LEG_WWUN: { set: 'mci', name: 'tank' },
  LEG_RENA: { set: 'mci', name: 'palette' },
  LEG_WWDE: { set: 'mci', name: 'parachute' },
  LEG_RESI: { set: 'mci', name: 'radio' },
  LEG_AVIA: { set: 'mci', name: 'airplane' },
  LEG_GUTE: { set: 'mci', name: 'book-open-variant' },
  LEG_INDU: { set: 'mci', name: 'factory' },
  LEG_REVO: { set: 'mci', name: 'flag-variant' },
  LEG_ENLI: { set: 'mci', name: 'lightbulb-on' },
  // Mythologies
  LEG_BEST: { set: 'mci', name: 'unicorn' },
  LEG_ATLA: { set: 'mci', name: 'city-variant' },
  LEG_JAPA: { set: 'mci', name: 'fan' },
  LEG_ARTH: { set: 'mci', name: 'sword' },
  LEG_MESO: { set: 'mci', name: 'pyramid' },
  LEG_AMER: { set: 'mci', name: 'feather' },
  LEG_POLY: { set: 'mci', name: 'waves' },
  LEG_MAYA: { set: 'mci', name: 'pyramid' },
  LEG_CELT: { set: 'mci', name: 'clover' },
  LEG_CHIN: { set: 'mci', name: 'yin-yang' },
  LEG_EGYP: { set: 'mci', name: 'eye' },
  LEG_GREE: { set: 'mci', name: 'lightning-bolt' },
  LEG_HIND: { set: 'mci', name: 'temple-hindu' },
  LEG_NORS: { set: 'mci', name: 'axe' },
  LEG_PERS: { set: 'mci', name: 'fire' },
  LEG_ROME: { set: 'mci', name: 'pillar' },
  LEG_SLAV: { set: 'mci', name: 'snowflake' },
  LEG_AFRI: { set: 'mci', name: 'music' },
  LEG_BIBL: { set: 'mci', name: 'cross' },
  LEG_ABO: { set: 'mci', name: 'weather-sunny' },
  // Espace & Univers
  LAB_BANG: { set: 'mci', name: 'creation' },
  LAB_COME: { set: 'mci', name: 'star-shooting' },
  LAB_CONZ: { set: 'mci', name: 'star-four-points' },
  LAB_NEUT: { set: 'mci', name: 'atom' },
  LAB_EXOP: { set: 'mci', name: 'earth' },
  LAB_ROKT: { set: 'mci', name: 'rocket-launch' },
  LAB_DYSO: { set: 'mci', name: 'orbit' },
  LAB_MOON: { set: 'mci', name: 'moon-waning-crescent' },
  LAB_MILK: { set: 'mci', name: 'creation' },
  LAB_MARS: { set: 'mci', name: 'earth' },
  LAB_DARK: { set: 'mci', name: 'circle-opacity' },
  LAB_NEBU: { set: 'mci', name: 'weather-fog' },
  LAB_SATE: { set: 'mci', name: 'satellite-variant' },
  LAB_STTN: { set: 'mci', name: 'space-station' },
  LAB_SOLR: { set: 'mci', name: 'white-balance-sunny' },
  LAB_EYES: { set: 'mci', name: 'telescope' },
  LAB_TIME: { set: 'mci', name: 'clock-fast' },
  LAB_HOLE: { set: 'mci', name: 'circle-double' },
  LAB_ALIE: { set: 'mci', name: 'alien' },
  LAB_WARP: { set: 'mci', name: 'star-crescent' },
  // Physique & Chimie
  LAB_PHPH: { set: 'mci', name: 'flask' },
  LAB_ALCH: { set: 'mci', name: 'flask-round-bottom' },
  LAB_ATOM: { set: 'mci', name: 'atom' },
  LAB_ORGA: { set: 'mci', name: 'molecule' },
  LAB_CRYG: { set: 'mci', name: 'snowflake' },
  LAB_DYNA: { set: 'mci', name: 'waves' },
  LAB_ELEC: { set: 'mci', name: 'lightning-bolt' },
  LAB_PLAS: { set: 'mci', name: 'fire' },
  LAB_FUSE: { set: 'mci', name: 'white-balance-sunny' },
  LAB_GRAV: { set: 'mci', name: 'apple' },
  LAB_MAGN: { set: 'mci', name: 'magnet' },
  LAB_MOLE: { set: 'mci', name: 'molecule' },
  LAB_NUKE: { set: 'mci', name: 'radioactive' },
  LAB_WAVE: { set: 'mci', name: 'sine-wave' },
  LAB_PHOT: { set: 'mci', name: 'lightbulb-on' },
  LAB_PQUA: { set: 'mci', name: 'atom-variant' },
  LAB_REAC: { set: 'mci', name: 'fire' },
  LAB_SUPR: { set: 'mci', name: 'magnet' },
  LAB_PERI: { set: 'mci', name: 'table' },
  LAB_THER: { set: 'mci', name: 'thermometer' },
  // Tech & IA
  LAB_DATA: { set: 'mci', name: 'database' },
  LAB_BIOH: { set: 'mci', name: 'dna' },
  LAB_BLOC: { set: 'mci', name: 'link-variant' },
  LAB_CLOD: { set: 'mci', name: 'cloud' },
  LAB_HACK: { set: 'mci', name: 'shield-lock' },
  LAB_DEEP: { set: 'mci', name: 'web' },
  LAB_ETIK: { set: 'mci', name: 'scale-balance' },
  LAB_CHIP: { set: 'mci', name: 'chip' },
  LAB_PRNT: { set: 'mci', name: 'printer-3d' },
  LAB_QUAN: { set: 'mci', name: 'atom-variant' },
  LAB_INTA: { set: 'mci', name: 'robot' },
  LAB_CODE: { set: 'mci', name: 'code-braces' },
  LAB_META: { set: 'mci', name: 'virtual-reality' },
  LAB_NANO: { set: 'mci', name: 'molecule' },
  LAB_CONN: { set: 'mci', name: 'devices' },
  LAB_AUGM: { set: 'mci', name: 'glasses' },
  LAB_NEUR: { set: 'mci', name: 'brain' },
  LAB_ROBO: { set: 'mci', name: 'robot-industrial' },
  LAB_CYBG: { set: 'mci', name: 'head-cog' },
  LAB_AUTO: { set: 'mci', name: 'car-connected' },
  // Gastronomie
  GLO_SUSH: { set: 'mci', name: 'fish' },
  GLO_PAIN: { set: 'mci', name: 'bread-slice' },
  GLO_CAFE: { set: 'mci', name: 'coffee' },
  GLO_MAGH: { set: 'mci', name: 'pot-steam' },
  GLO_THAI: { set: 'mci', name: 'chili-mild' },
  GLO_SUCR: { set: 'mci', name: 'cupcake' },
  GLO_FROM: { set: 'mci', name: 'cheese' },
  GLO_FRUI: { set: 'mci', name: 'fruit-pineapple' },
  GLO_VEGE: { set: 'mci', name: 'leaf' },
  GLO_GRIL: { set: 'mci', name: 'grill' },
  GLO_GAST: { set: 'mci', name: 'chef-hat' },
  GLO_COCK: { set: 'mci', name: 'glass-cocktail' },
  GLO_PIZZ: { set: 'mci', name: 'pizza' },
  GLO_EPIC: { set: 'mci', name: 'shaker' },
  GLO_INDI: { set: 'mci', name: 'chili-hot' },
  GLO_STRE: { set: 'mci', name: 'food' },
  GLO_CHOC: { set: 'mci', name: 'candy' },
  GLO_MERI: { set: 'mci', name: 'fish' },
  GLO_VIGN: { set: 'mci', name: 'glass-wine' },
  GLO_MEXI: { set: 'mci', name: 'chili-mild' },
  // Langues & Cultures
  GLO_ARTI: { set: 'mci', name: 'hammer-wrench' },
  GLO_SAMO: { set: 'mci', name: 'sword' },
  GLO_CARN: { set: 'mci', name: 'domino-mask' },
  GLO_VETM: { set: 'mci', name: 'tshirt-crew' },
  GLO_DANS: { set: 'mci', name: 'human-female-dance' },
  GLO_ECRI: { set: 'mci', name: 'fountain-pen-tip' },
  GLO_FEST: { set: 'mci', name: 'party-popper' },
  GLO_FOLK: { set: 'mci', name: 'music-note' },
  GLO_HABI: { set: 'mci', name: 'home' },
  GLO_MASQ: { set: 'mci', name: 'drama-masks' },
  GLO_VIKI: { set: 'mci', name: 'axe' },
  GLO_MUSI: { set: 'mci', name: 'music' },
  GLO_MYTH: { set: 'mci', name: 'lightning-bolt' },
  GLO_AUTO: { set: 'mci', name: 'account-group' },
  GLO_LANG: { set: 'mci', name: 'translate' },
  GLO_BOLL: { set: 'mci', name: 'television' },
  GLO_SAGE: { set: 'mci', name: 'meditation' },
  GLO_ETIQ: { set: 'mci', name: 'hand-heart' },
  GLO_ESPO: { set: 'mci', name: 'trophy' },
  GLO_SYMB: { set: 'mci', name: 'yin-yang' },
  // Voyage & Géo
  GLO_CAPI: { set: 'mci', name: 'city-variant' },
  GLO_DESE: { set: 'mci', name: 'cactus' },
  GLO_NORD: { set: 'mci', name: 'snowflake' },
  GLO_FLEU: { set: 'mci', name: 'waves' },
  GLO_ISLA: { set: 'mci', name: 'island' },
  GLO_ITAL: { set: 'mci', name: 'pizza' },
  GLO_FRAN: { set: 'mci', name: 'eiffel-tower' },
  GLO_JAPO: { set: 'mci', name: 'fan' },
  GLO_ANTI: { set: 'mci', name: 'pyramid' },
  GLO_MONU: { set: 'mci', name: 'bank' },
  GLO_OCEN: { set: 'mci', name: 'palm-tree' },
  GLO_OCEA: { set: 'mci', name: 'waves' },
  GLO_PARC: { set: 'mci', name: 'pine-tree' },
  GLO_PONT: { set: 'mci', name: 'bridge' },
  GLO_ASIE: { set: 'mci', name: 'road-variant' },
  GLO_SUMM: { set: 'mci', name: 'terrain' },
  GLO_AMER: { set: 'mci', name: 'earth' },
  GLO_AFRI: { set: 'mci', name: 'earth' },
  GLO_ETAT: { set: 'mci', name: 'flag-variant' },
  GLO_VILL: { set: 'mci', name: 'city' },
  // Corps Humain
  LIF_ANAT: { set: 'mci', name: 'human' },
  LIF_AUDI: { set: 'mci', name: 'ear-hearing' },
  LIF_BIOT: { set: 'mci', name: 'dna' },
  LIF_CELL: { set: 'mci', name: 'circle-double' },
  LIF_CERV: { set: 'mci', name: 'brain' },
  LIF_COEU: { set: 'mci', name: 'heart-pulse' },
  LIF_GENE: { set: 'mci', name: 'dna' },
  LIF_HORM: { set: 'mci', name: 'flask' },
  LIF_IMMU: { set: 'mci', name: 'shield-plus' },
  LIF_SENS: { set: 'mci', name: 'hand-wave' },
  LIF_LONG: { set: 'mci', name: 'infinity' },
  LIF_MEMO: { set: 'mci', name: 'head-cog' },
  LIF_MICR: { set: 'mci', name: 'bacteria' },
  LIF_MUSC: { set: 'mci', name: 'arm-flex' },
  LIF_NUTR: { set: 'mci', name: 'food-apple' },
  LIF_PEAU: { set: 'mci', name: 'hand-back-right' },
  LIF_PSYC: { set: 'mci', name: 'head-question' },
  LIF_RESP: { set: 'mci', name: 'lungs' },
  LIF_SOMM: { set: 'mci', name: 'sleep' },
  LIF_VISI: { set: 'mci', name: 'eye' },
  // Monde Animal
  LIF_ABYS: { set: 'mci', name: 'fish' },
  LIF_AMPH: { set: 'mci', name: 'turtle' },
  LIF_ARAC: { set: 'mci', name: 'spider' },
  LIF_CAMO: { set: 'mci', name: 'eye-off' },
  LIF_CANI: { set: 'mci', name: 'dog' },
  LIF_DINO: { set: 'mci', name: 'bone' },
  LIF_FELI: { set: 'mci', name: 'cat' },
  LIF_INSE: { set: 'mci', name: 'bug' },
  LIF_INVE: { set: 'mci', name: 'snail' },
  LIF_MEMA: { set: 'mci', name: 'dolphin' },
  LIF_MIGR: { set: 'mci', name: 'bird' },
  LIF_ARCT: { set: 'mci', name: 'penguin' },
  LIF_OCEA: { set: 'mci', name: 'waves' },
  LIF_OISE: { set: 'mci', name: 'bird' },
  LIF_PRED: { set: 'mci', name: 'shark-fin' },
  LIF_PRIM: { set: 'mci', name: 'paw' },
  LIF_REPT: { set: 'mci', name: 'snake' },
  LIF_SAVA: { set: 'mci', name: 'elephant' },
  LIF_SYMB: { set: 'mci', name: 'link-variant' },
  LIF_NOCT: { set: 'mci', name: 'owl' },
  // Nature & Écologie
  LIF_ADAP: { set: 'mci', name: 'swap-horizontal' },
  LIF_ARBR: { set: 'mci', name: 'tree' },
  LIF_BIOD: { set: 'mci', name: 'leaf' },
  LIF_FONG: { set: 'mci', name: 'mushroom' },
  LIF_CLIM: { set: 'mci', name: 'weather-partly-cloudy' },
  LIF_DESE: { set: 'mci', name: 'cactus' },
  LIF_ECOL: { set: 'mci', name: 'recycle' },
  LIF_EVOL: { set: 'mci', name: 'sprout' },
  LIF_FLOR: { set: 'mci', name: 'flower' },
  LIF_CATA: { set: 'mci', name: 'weather-hurricane' },
  LIF_FORA: { set: 'mci', name: 'forest' },
  LIF_JUNG: { set: 'mci', name: 'palm-tree' },
  LIF_MANG: { set: 'mci', name: 'waves' },
  LIF_MONT: { set: 'mci', name: 'terrain' },
  LIF_PHOT: { set: 'mci', name: 'white-balance-sunny' },
  LIF_PHAR: { set: 'mci', name: 'leaf' },
  LIF_POLL: { set: 'mci', name: 'bee-flower' },
  LIF_RIVI: { set: 'mci', name: 'waves' },
  LIF_SAIS: { set: 'mci', name: 'weather-sunny' },
  LIF_SOLS: { set: 'mci', name: 'shovel' },
  // Littérature
  MIN_RUSS: { set: 'mci', name: 'book-open-variant' },
  MIN_BDCM: { set: 'mci', name: 'book-open-page-variant' },
  MIN_BEAT: { set: 'mci', name: 'road-variant' },
  MIN_BEST: { set: 'mci', name: 'trophy' },
  MIN_CLAS: { set: 'mci', name: 'bookshelf' },
  MIN_MANG: { set: 'mci', name: 'book-open-variant' },
  MIN_DRAM: { set: 'mci', name: 'drama-masks' },
  MIN_EPIC: { set: 'mci', name: 'sword' },
  MIN_VICT: { set: 'mci', name: 'hat-fedora' },
  MIN_EXIS: { set: 'mci', name: 'thought-bubble' },
  MIN_FANT: { set: 'mci', name: 'castle' },
  MIN_KIDS: { set: 'mci', name: 'teddy-bear' },
  MIN_FRAN: { set: 'mci', name: 'feather' },
  MIN_MYTH: { set: 'mci', name: 'lightning-bolt' },
  MIN_POET: { set: 'mci', name: 'fountain-pen' },
  MIN_NOIR: { set: 'mci', name: 'magnify' },
  MIN_NOBE: { set: 'mci', name: 'medal' },
  MIN_GOTH: { set: 'mci', name: 'skull' },
  MIN_SCIF: { set: 'mci', name: 'rocket-launch' },
  MIN_SHAK: { set: 'mci', name: 'drama-masks' },
  // Maths & Logique
  MIN_ALGE: { set: 'mci', name: 'function-variant' },
  MIN_ALGO: { set: 'mci', name: 'code-braces' },
  MIN_ANAL: { set: 'mci', name: 'chart-line' },
  MIN_CALC: { set: 'mci', name: 'calculator' },
  MIN_CRYP: { set: 'mci', name: 'lock' },
  MIN_ENIG: { set: 'mci', name: 'puzzle' },
  MIN_HIST: { set: 'mci', name: 'book-open-variant' },
  MIN_FRAC: { set: 'mci', name: 'snowflake' },
  MIN_GEOM: { set: 'mci', name: 'shape' },
  MIN_ARTI: { set: 'mci', name: 'robot' },
  MIN_LOGI: { set: 'mci', name: 'head-cog' },
  MIN_ASTR: { set: 'mci', name: 'orbit' },
  MIN_GOLD: { set: 'mci', name: 'orbit' },
  MIN_PRIM: { set: 'mci', name: 'numeric' },
  MIN_PHYS: { set: 'mci', name: 'atom' },
  MIN_STAT: { set: 'mci', name: 'dice-multiple' },
  MIN_SETS: { set: 'mci', name: 'set-center' },
  MIN_GAME: { set: 'mci', name: 'chess-knight' },
  MIN_TOPO: { set: 'mci', name: 'vector-curve' },
  MIN_TRIGO: { set: 'mci', name: 'triangle-outline' },
  // Philo & Psycho
  MIN_BEHA: { set: 'mci', name: 'account-cog' },
  MIN_EPIS: { set: 'mci', name: 'magnify' },
  MIN_ETHI: { set: 'mci', name: 'scale-balance' },
  MIN_EMOT: { set: 'mci', name: 'heart-pulse' },
  MIN_LUMI: { set: 'mci', name: 'lightbulb-on' },
  MIN_META: { set: 'mci', name: 'infinity' },
  MIN_NEUR: { set: 'mci', name: 'brain' },
  MIN_NIHI: { set: 'mci', name: 'circle-off-outline' },
  MIN_PHEN: { set: 'mci', name: 'eye' },
  MIN_POLI: { set: 'mci', name: 'gavel' },
  MIN_FREU: { set: 'mci', name: 'sofa' },
  MIN_DEVE: { set: 'mci', name: 'human-male-child' },
  MIN_HAPP: { set: 'mci', name: 'emoticon-happy' },
  MIN_SOCI: { set: 'mci', name: 'account-group' },
  MIN_RHET: { set: 'mci', name: 'comment-quote' },
  MIN_GREE: { set: 'mci', name: 'pillar' },
  MIN_EAST: { set: 'mci', name: 'yin-yang' },
  MIN_COGN: { set: 'mci', name: 'head-cog' },
  MIN_STOI: { set: 'mci', name: 'pillar' },
};

type Props = {
  emoji?: string;
  themeId?: string;
  size: number;
  color: string;
  type?: 'super' | 'cluster' | 'theme';
};

export default function CategoryIcon({ emoji, themeId, size, color, type = 'super' }: Props) {
  // Theme ID lookup first
  if (themeId && THEME_ICON_MAP[themeId]) {
    const icon = THEME_ICON_MAP[themeId];
    return renderIcon(icon, size, color);
  }

  // Emoji-based lookup — try primary map first, then fallback to all maps
  if (emoji) {
    const primaryMap = type === 'cluster' ? CLUSTER_ICON_MAP : SUPER_ICON_MAP;
    const icon = primaryMap[emoji] || SUPER_ICON_MAP[emoji] || CLUSTER_ICON_MAP[emoji];
    if (icon) return renderIcon(icon, size, color);
    return <Text style={{ fontSize: size * 0.8 }}>{emoji}</Text>;
  }

  return null;
}

function renderIcon(icon: IconDef, size: number, color: string) {
  switch (icon.set) {
    case 'mci':
      return <MaterialCommunityIcons name={icon.name as any} size={size} color={color} />;
    case 'ion':
      return <Ionicons name={icon.name as any} size={size} color={color} />;
    case 'fa5':
      return <FontAwesome5 name={icon.name} size={size} color={color} />;
  }
}
